// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mysqlc

type Clinic struct {
	ID         uint32
	UserID     uint32
	Name       string
	Location   string
	BusinessNo string
	IsVerified uint8
}

type Role struct {
	ID          uint8
	Description string
}

type User struct {
	ID         uint32
	GivenName  string
	FamilyName string
	Email      string
	Password   string
	RoleID     uint8
}
