// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mysqlc

type User struct {
	ID         int32
	GivenName  string
	FamilyName string
	Email      string
	Password   string
}
